import { useEffect, useRef, useState } from 'react';
import { Hero } from '../components/Hero';
import { useGsapContext } from '../hooks/useGsapContext';
import { gsap } from '../lib/gsap';
import { images as img } from '../data/images';
import { PageLink as Link } from './shared';

const sectionLinks=[['home-opening','Abertura'],['home-essence','Essência'],['home-stay','Permanecer'],['home-rooms','Alojamentos'],['home-spa','Spa'],['home-table','Mesa'],['home-reserve','Reservar']];
function SectionNav(){const[active,setActive]=useState('home-opening');useEffect(()=>{const elements=sectionLinks.map(([id])=>document.getElementById(id)).filter(Boolean);const observer=new IntersectionObserver(entries=>{const visible=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>b.intersectionRatio-a.intersectionRatio)[0];if(visible)setActive(visible.target.id)},{rootMargin:'-32% 0px -48%',threshold:[0,.1,.35,.6]});elements.forEach(element=>observer.observe(element));return()=>observer.disconnect()},[]);const jump=id=>document.getElementById(id)?.scrollIntoView({behavior:'smooth',block:'start'});return <nav className="section-nav" aria-label="Secções da homepage">{sectionLinks.map(([id,label],index)=><button key={id} className={active===id?'active':''} onClick={()=>jump(id)} aria-label={`Ir para ${label}`}><i/><span><small>0{index+1}</small>{label}</span></button>)}</nav>}
export function Home({go,canPlay=true,headerRef}){const root=useRef(null);useGsapContext(root,()=>{const mm=gsap.matchMedia();mm.add('(prefers-reduced-motion: no-preference)',()=>{gsap.utils.toArray('.scroll-reveal').forEach(section=>{gsap.from(Array.from(section.children),{autoAlpha:0,y:70,duration:1.15,stagger:.12,ease:'power3.out',scrollTrigger:{trigger:section,start:'top 78%',once:true}})});gsap.from('.preview>img',{clipPath:'inset(12%)',scale:1.08,duration:1.5,ease:'power3.out',scrollTrigger:{trigger:'.preview',start:'top 75%',once:true}})});return()=>mm.revert()});return <div ref={root}><SectionNav/><div id="home-opening"><Hero canPlay={canPlay} headerRef={headerRef}/></div><section id="home-essence" className="manifest scroll-reveal"><small>Juniper não é um lugar para visitar.</small><h2>É um lugar para <em>sentir</em> — devagar, com todos os sentidos.</h2><div><span>Arquitetura silenciosa</span><span>Cozinha da terra</span><span>Rituais de bem-estar</span></div></section><section id="home-stay" className="preview scroll-reveal"><img src={img.garden} alt="Pátio privado da Garden House"/><div><small>01 / Permanecer</small><h2>Espaços que<br/>guardam a calma.</h2><p>Materiais naturais, luz filtrada e a intimidade rara de não precisar de mais nada.</p><Link to="/suites" go={go}>Explorar suites</Link></div></section></div>}
